<?php

declare(strict_types=1);

/**
 * @file
 * Provides a deletion record entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function audit_theme(): array {
  return [
    'deletion_record' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for deletion record templates.
 *
 * Default template: deletion-record.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the deletion record information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_deletion_record(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function audit_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_reassign':
      // Anonymize deletion records.
      $storage = \Drupal::entityTypeManager()->getStorage('deletion_record');
      $deletion_record_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($deletion_record_ids) as $deletion_record) {
        $deletion_record->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function audit_user_predelete(UserInterface $account): void {
  // Delete deletion records that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('deletion_record');
  $deletion_record_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($deletion_record_ids)
  );
  
  // Delete old revisions.
  $deletion_record_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($deletion_record_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}